implemented getting frame and adding ROI
MaximChernyak98/CountWorkTime_bot pull request #2
Opened 2020-09-28 15:02 UTC by MaximChernyak98

Привет, Муслим
Просьба сделать код-ревью и проверить все ли так организовал в проекте

2020-09-29 12:58 UTC, n05tr0m0 requested changes
Подправь и закоммить опять, я посмотрю

2020-09-29 12:58 UTC, n05tr0m0 commented on CountWorkTime_bot.py
>  # files import
Это комментарий лишний, его можно удалить.

2020-09-29 12:58 UTC, n05tr0m0 commented on CountWorkTime_bot.py
>  import cv2.cv2 as cv2
Тут можно просто `import cv2`, будет работать

2020-09-29 12:58 UTC, n05tr0m0 commented on utils/start_caption.py
>                                      face_cascade_xml)
Можно записать в одну строку, так читаемее:<br />
`path_to_face_cascade = os.path.join(current_dir, '..', 'cascades', 'data', face_cascade_xml)`<br />
Имеет смысл переноса, когда ты вмещаешься в 80/120 символов. 
120 символов обычно длина строк в современных проектах
80 символов было принято, потому что раньше мониторы и разрешение экранов были скудными и длинные строки было не удобно читать.
[Вот ссылочка по этому поводу](https://devman.org/encyclopedia/python_basics/python_basics_formatting/)

2020-09-29 12:58 UTC, n05tr0m0 commented on utils/start_caption.py
> +    videostream_for_caption = cv2.VideoCapture(0)
я бы просто назвал `video_capture` - лаконичнее и понятно что делает

2020-09-29 12:58 UTC, n05tr0m0 commented on utils/get_frame.py
> +# import numpy as np
Если ты не используешь импорты, в финальной версии перед коммитом удаляй всё лишнее.

2020-09-29 12:58 UTC, n05tr0m0 commented on utils/get_frame.py
> +import cv2.cv2 as cv2
тут тоже самое, работает через `import cv2`

2020-09-29 12:58 UTC, n05tr0m0 commented on utils/get_frame.py
> +    # get gray frame
Имеет смысл оставлять комментарии, когда не понятно, что делает код с первого взгляда или когда большая вложенность и чтобы понять написанный код, нужно прошерстить вглубь функций

2020-09-29 12:58 UTC, n05tr0m0 commented on CountWorkTime_bot.py
> +from utils.start_caption import start_caption_frame
Чтобы не плодить кучу файлов, я бы сделал файл `utils.py` и туда запихнул бы все утилиты, а импортировал бы `from utils import get_frame, start_caption_frame`
А то так ты замучаешься в будущем, когда проект разрастётся

2020-09-29 12:58 UTC, n05tr0m0 commented on CountWorkTime_bot.py
> +from utils.start_caption import start_caption_frame
На мой взгляд по файлам можно разделять когда проект большой и в одном файле писать всё не хорошо и запутано, можно выделять логические сущности в отдельные категории и разделить код на файлы по этим категориям

2020-09-29 12:58 UTC, n05tr0m0 commented on utils/get_frame.py
> +        # set ROI-settings
Тут та же тема с комментариями

2020-09-29 12:58 UTC, n05tr0m0 commented on utils/get_frame.py
> +        # add ROI to image
и тут про комметы

2020-09-29 12:58 UTC, n05tr0m0 commented on CountWorkTime_bot.py
>  import cv2.cv2 as cv2
на первой строке лишний комментарий, надо убрать

2020-09-29 20:02 UTC, MaximChernyak98 reviewed
Постарался учесть замечания, Муслим

2020-09-29 20:02 UTC, MaximChernyak98 commented on CountWorkTime_bot.py
>  # files import
убрал

2020-09-29 20:02 UTC, MaximChernyak98 commented on CountWorkTime_bot.py
> +from utils.start_caption import start_caption_frame
сделал, просьба намекнуть когда стоит уже разбивать на отдельные файлы:)

2020-09-29 20:02 UTC, MaximChernyak98 commented on utils/get_frame.py
> +# import numpy as np
да, в примере дядько добавлял, пробовал будет ли работать без numpy, а убрать забыл

2020-09-29 20:02 UTC, MaximChernyak98 commented on CountWorkTime_bot.py
>  import cv2.cv2 as cv2
Да, работать будет но пайчарм тогда вот так светится
![image](https://user-images.githubusercontent.com/62598232/94607622-d36d9b80-02a4-11eb-9368-2d3d3d7ef8fd.png)

На SO смотрел, пробовал - не помогло
https://stackoverflow.com/questions/34365044/pycharm-does-not-recognize-cv2-as-a-module

Поэтому оставлю import cv2.cv2 as cv2

2020-09-29 20:02 UTC, MaximChernyak98 commented on utils/get_frame.py
> +import cv2.cv2 as cv2
аналогично светиться, оставляю

2020-09-29 20:02 UTC, MaximChernyak98 commented on utils/get_frame.py
> +    # get gray frame
Просто предыдущий куратор говорил, что такое помогает:)
Понимаю, что дело опыта, но пока не чувствую где нужен коммент, где нет:(
видосы от Гриши смотрел, пока не помогло видимо:)

2020-09-29 20:02 UTC, MaximChernyak98 commented on utils/start_caption.py
>                                      face_cascade_xml)
Про инфу 80 символов для старых компов спасибо, не знал, но я работаю на ноуте + комфортнее с большим шрифтом
как раз 80-90 умещается с открытым деревом файлов
переделал по статье - имхо читается лучше, но выглядит странно
это же не криминал, если буду умещать все в 80?

2020-09-29 20:02 UTC, MaximChernyak98 commented on utils/start_caption.py
> +    videostream_for_caption = cv2.VideoCapture(0)
поправил

2020-09-29 20:21 UTC, n05tr0m0 requested changes
Подправь ещё и закомить

2020-09-29 20:21 UTC, n05tr0m0 commented on CountWorkTime_bot.py
>  import cv2.cv2 as cv2
пусть светится, тебя это не должно отвлекать
либо можешь просто убрать подсветку таких моментов в линтере пайчарма

2020-09-29 20:21 UTC, n05tr0m0 commented on CountWorkTime_bot.py
>  import cv2.cv2 as cv2
Так же ты не убрал лишний комментарий на первой строке `#pip import`

2020-09-29 20:21 UTC, n05tr0m0 commented on CountWorkTime_bot.py
>          # Display the resulting frame
тоже не нужный комментарий

2020-09-29 20:21 UTC, n05tr0m0 commented on CountWorkTime_bot.py
>      # When everything done, release the capture
И этот тоже

2020-09-29 20:21 UTC, n05tr0m0 commented on utils.py
> +# std import
Этот комментарий тоже не нужен

2020-09-29 20:21 UTC, n05tr0m0 commented on utils.py
> +# pip import
И этот

2020-09-29 20:21 UTC, n05tr0m0 commented on utils.py
> +# variables
И этот

2020-09-29 20:21 UTC, n05tr0m0 commented on utils.py
> +# get path to using cascade (in any system)
и этот

2020-09-29 20:21 UTC, n05tr0m0 commented on utils.py
> +# get path to using cascade (in any system)
Не нужны они по той причине, что код читабельный и из него всё и так ясно.
Писать очевидные комментарии к коду плохо, не делай так

2020-09-29 20:21 UTC, n05tr0m0 commented on utils.py
> +import cv2.cv2 as cv2
Это не корректный импорт, так делать плохо, не делай так.
Сделай как надо либо` import <module name>`, либо from `<module name> import <another module name>`

2020-09-29 20:21 UTC, n05tr0m0 commented on utils.py
> +    return frame
после последний строчки кода оставляй пустую строку `PEP8`

2020-10-01 12:00 UTC, MaximChernyak98 commented on CountWorkTime_bot.py
>          # Display the resulting frame
ок

2020-10-01 12:00 UTC, MaximChernyak98 commented on CountWorkTime_bot.py
>      # When everything done, release the capture
ок

2020-10-01 12:01 UTC, MaximChernyak98 commented on utils.py
> +# pip import
ок

2020-10-01 12:01 UTC, MaximChernyak98 commented on utils.py
> +# variables
ок

2020-10-01 12:01 UTC, MaximChernyak98 commented on utils.py
> +# get path to using cascade (in any system)
ок, ты намекни когда по твоему нужно будет добавить коммент

2020-10-01 12:02 UTC, MaximChernyak98 commented on utils.py
> +    return frame
ок

2020-10-01 12:06 UTC, MaximChernyak98 commented on utils.py
> +import cv2.cv2 as cv2
ок

2020-10-01 12:06 UTC, MaximChernyak98 commented on utils.py
> +# std import
ок

2020-10-01 12:07 UTC, MaximChernyak98 commented
Постарался учесть замечания, Муслим

2020-10-01 12:13 UTC, n05tr0m0 commented on utils.py
> +# get path to using cascade (in any system)
@MaximChernyak98 вот [тут](https://devman.org/encyclopedia/python_basics/python_basics_comments/) хорошо расписано про комментирование кода. Почитай

2020-10-01 12:20 UTC, n05tr0m0 requested changes
ещё один момент я прокомментировал, проверь и присылай

2020-10-01 12:20 UTC, n05tr0m0 commented on utils.py
> +    '..',
зачем тут` '..',`?
Ты проверял свой пусть в переменной `path_to_face_cascade`?

2020-10-01 13:24 UTC, n05tr0m0 reviewed
Прокомментируй

2020-10-01 13:24 UTC, n05tr0m0 commented on CountWorkTime_bot.py
> +face_counter = 0
А зачем ввёл не используемую переменную?

2020-10-02 14:17 UTC, MaximChernyak98 commented on utils.py
> +    '..',
да, с перемещением функций в utils.py '..' не нужны, убрал

2020-10-02 14:18 UTC, MaximChernyak98 commented on CountWorkTime_bot.py
> +face_counter = 0
добавил до создания новой ветки, убрал

2020-10-02 14:22 UTC, MaximChernyak98 commented
Привет, Муслим.
Прокомментировал.
В тексте коммита заюзал "#3" - он подцепил номер issue, сделал не преднамеренно, не знал, что так работает.
Не обращай внимания

2020-10-02 14:55 UTC, n05tr0m0 approved these changes

2020-10-02 14:55 UTC, merged